//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace PSOG.Bizc.WXWeb {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WXServiceSoap", Namespace="http://PSOG.WEIXIN.com/")]
    public partial class WXService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendInfoToUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendAlarmNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SmsSendFuncOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOAuth2UrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOAuth2UserIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WXService() {
            this.Url = global::PSOG.Bizc.Properties.Settings.Default.PSOG_Bizc_WXWeb_WXService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CreateUserCompletedEventHandler CreateUserCompleted;
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        public event DeleteUserCompletedEventHandler DeleteUserCompleted;
        
        /// <remarks/>
        public event SendInfoToUserCompletedEventHandler SendInfoToUserCompleted;
        
        /// <remarks/>
        public event SendAlarmNewsCompletedEventHandler SendAlarmNewsCompleted;
        
        /// <remarks/>
        public event SmsSendFuncCompletedEventHandler SmsSendFuncCompleted;
        
        /// <remarks/>
        public event GetOAuth2UrlCompletedEventHandler GetOAuth2UrlCompleted;
        
        /// <remarks/>
        public event GetOAuth2UserIdCompletedEventHandler GetOAuth2UserIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/HelloWorld", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/CreateUser", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateUser(WeiXinUserData weiXinUserData) {
            object[] results = this.Invoke("CreateUser", new object[] {
                        weiXinUserData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateUserAsync(WeiXinUserData weiXinUserData) {
            this.CreateUserAsync(weiXinUserData, null);
        }
        
        /// <remarks/>
        public void CreateUserAsync(WeiXinUserData weiXinUserData, object userState) {
            if ((this.CreateUserOperationCompleted == null)) {
                this.CreateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateUserOperationCompleted);
            }
            this.InvokeAsync("CreateUser", new object[] {
                        weiXinUserData}, this.CreateUserOperationCompleted, userState);
        }
        
        private void OnCreateUserOperationCompleted(object arg) {
            if ((this.CreateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/UpdateUser", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateUser(WeiXinUserData weiXinUserData) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        weiXinUserData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserAsync(WeiXinUserData weiXinUserData) {
            this.UpdateUserAsync(weiXinUserData, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(WeiXinUserData weiXinUserData, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        weiXinUserData}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/DeleteUser", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeleteUser(string userId) {
            object[] results = this.Invoke("DeleteUser", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string userId) {
            this.DeleteUserAsync(userId, null);
        }
        
        /// <remarks/>
        public void DeleteUserAsync(string userId, object userState) {
            if ((this.DeleteUserOperationCompleted == null)) {
                this.DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUserOperationCompleted);
            }
            this.InvokeAsync("DeleteUser", new object[] {
                        userId}, this.DeleteUserOperationCompleted, userState);
        }
        
        private void OnDeleteUserOperationCompleted(object arg) {
            if ((this.DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUserCompleted(this, new DeleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/SendInfoToUser", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendInfoToUser(string userId, string content, string applicationId) {
            this.Invoke("SendInfoToUser", new object[] {
                        userId,
                        content,
                        applicationId});
        }
        
        /// <remarks/>
        public void SendInfoToUserAsync(string userId, string content, string applicationId) {
            this.SendInfoToUserAsync(userId, content, applicationId, null);
        }
        
        /// <remarks/>
        public void SendInfoToUserAsync(string userId, string content, string applicationId, object userState) {
            if ((this.SendInfoToUserOperationCompleted == null)) {
                this.SendInfoToUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendInfoToUserOperationCompleted);
            }
            this.InvokeAsync("SendInfoToUser", new object[] {
                        userId,
                        content,
                        applicationId}, this.SendInfoToUserOperationCompleted, userState);
        }
        
        private void OnSendInfoToUserOperationCompleted(object arg) {
            if ((this.SendInfoToUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendInfoToUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/SendAlarmNews", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendAlarmNews(NewsArticle newsArticle, string userId, string applicationId) {
            this.Invoke("SendAlarmNews", new object[] {
                        newsArticle,
                        userId,
                        applicationId});
        }
        
        /// <remarks/>
        public void SendAlarmNewsAsync(NewsArticle newsArticle, string userId, string applicationId) {
            this.SendAlarmNewsAsync(newsArticle, userId, applicationId, null);
        }
        
        /// <remarks/>
        public void SendAlarmNewsAsync(NewsArticle newsArticle, string userId, string applicationId, object userState) {
            if ((this.SendAlarmNewsOperationCompleted == null)) {
                this.SendAlarmNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendAlarmNewsOperationCompleted);
            }
            this.InvokeAsync("SendAlarmNews", new object[] {
                        newsArticle,
                        userId,
                        applicationId}, this.SendAlarmNewsOperationCompleted, userState);
        }
        
        private void OnSendAlarmNewsOperationCompleted(object arg) {
            if ((this.SendAlarmNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendAlarmNewsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/SmsSendFunc", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SmsSendFunc(string strMsg, string[] MobileList) {
            object[] results = this.Invoke("SmsSendFunc", new object[] {
                        strMsg,
                        MobileList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SmsSendFuncAsync(string strMsg, string[] MobileList) {
            this.SmsSendFuncAsync(strMsg, MobileList, null);
        }
        
        /// <remarks/>
        public void SmsSendFuncAsync(string strMsg, string[] MobileList, object userState) {
            if ((this.SmsSendFuncOperationCompleted == null)) {
                this.SmsSendFuncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSmsSendFuncOperationCompleted);
            }
            this.InvokeAsync("SmsSendFunc", new object[] {
                        strMsg,
                        MobileList}, this.SmsSendFuncOperationCompleted, userState);
        }
        
        private void OnSmsSendFuncOperationCompleted(object arg) {
            if ((this.SmsSendFuncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SmsSendFuncCompleted(this, new SmsSendFuncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/GetOAuth2Url", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOAuth2Url(string url, string urlType) {
            object[] results = this.Invoke("GetOAuth2Url", new object[] {
                        url,
                        urlType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOAuth2UrlAsync(string url, string urlType) {
            this.GetOAuth2UrlAsync(url, urlType, null);
        }
        
        /// <remarks/>
        public void GetOAuth2UrlAsync(string url, string urlType, object userState) {
            if ((this.GetOAuth2UrlOperationCompleted == null)) {
                this.GetOAuth2UrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOAuth2UrlOperationCompleted);
            }
            this.InvokeAsync("GetOAuth2Url", new object[] {
                        url,
                        urlType}, this.GetOAuth2UrlOperationCompleted, userState);
        }
        
        private void OnGetOAuth2UrlOperationCompleted(object arg) {
            if ((this.GetOAuth2UrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOAuth2UrlCompleted(this, new GetOAuth2UrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PSOG.WEIXIN.com/GetOAuth2UserId", RequestNamespace="http://PSOG.WEIXIN.com/", ResponseNamespace="http://PSOG.WEIXIN.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOAuth2UserId(string code) {
            object[] results = this.Invoke("GetOAuth2UserId", new object[] {
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOAuth2UserIdAsync(string code) {
            this.GetOAuth2UserIdAsync(code, null);
        }
        
        /// <remarks/>
        public void GetOAuth2UserIdAsync(string code, object userState) {
            if ((this.GetOAuth2UserIdOperationCompleted == null)) {
                this.GetOAuth2UserIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOAuth2UserIdOperationCompleted);
            }
            this.InvokeAsync("GetOAuth2UserId", new object[] {
                        code}, this.GetOAuth2UserIdOperationCompleted, userState);
        }
        
        private void OnGetOAuth2UserIdOperationCompleted(object arg) {
            if ((this.GetOAuth2UserIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOAuth2UserIdCompleted(this, new GetOAuth2UserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PSOG.WEIXIN.com/")]
    public partial class WeiXinUserData {
        
        private string useridField;
        
        private string nameField;
        
        private int[] departmentField;
        
        private string positionField;
        
        private string mobileField;
        
        private string emailField;
        
        private string genderField;
        
        private WeiXinExtattr extattrField;
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int[] department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public WeiXinExtattr extattr {
            get {
                return this.extattrField;
            }
            set {
                this.extattrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PSOG.WEIXIN.com/")]
    public partial class WeiXinExtattr {
        
        private WeiXinAttrsItem[] attrsField;
        
        /// <remarks/>
        public WeiXinAttrsItem[] attrs {
            get {
                return this.attrsField;
            }
            set {
                this.attrsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PSOG.WEIXIN.com/")]
    public partial class WeiXinAttrsItem {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PSOG.WEIXIN.com/")]
    public partial class NewsArticle {
        
        private string picUrlField;
        
        private string urlField;
        
        private string descriptionField;
        
        private string titleField;
        
        /// <remarks/>
        public string picUrl {
            get {
                return this.picUrlField;
            }
            set {
                this.picUrlField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void CreateUserCompletedEventHandler(object sender, CreateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void DeleteUserCompletedEventHandler(object sender, DeleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SendInfoToUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SendAlarmNewsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void SmsSendFuncCompletedEventHandler(object sender, SmsSendFuncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SmsSendFuncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SmsSendFuncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetOAuth2UrlCompletedEventHandler(object sender, GetOAuth2UrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOAuth2UrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOAuth2UrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetOAuth2UserIdCompletedEventHandler(object sender, GetOAuth2UserIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOAuth2UserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOAuth2UserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591